ActionManager {
 Actions {
  Action CAV_HunterKillerSlew {
   Type Digital
   InputSource InputSourceSum "{6620DEADBEDA583A}" {
    Sources {
     InputSourceValue "{6620DEADBEDA583B}" {
      Input "keyboard:KC_NUMPAD2"
     }
    }
   }
  }
  Action CAV_HunterKillerCancel {
   Type Digital
   InputSource InputSourceSum "{6620DEADBEDA583C}" {
    Sources {
     InputSourceValue "{6620DEADBEDA583D}" {
      Input "keyboard:KC_NUMPAD3"
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterMovementContext {
   ActionRefs +{
    "CAV_HunterKillerSlew"
    "CAV_HunterKillerCancel"
   }
  }
  ActionContext CharacterLookContext {
   ActionRefs +{
    "CAV_HunterKillerSlew"
    "CAV_HunterKillerCancel"
   }
  }
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "CAV_HunterKillerSlew"
    "CAV_HunterKillerCancel"
   }
  }
 }
}