SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{68FE02177E9FCA09}" {
   Rules {
    EntityClassGarbageRule "{66260B320E27FFF2}" {
     Filter "Vehicle"
     OnlyDestroyed 1
     Lifetime 400
     PlayerDistance 150
    }
   }
  }
  HUDMarkerSystem "{68FE02175742A252}" {
   m_aHmdHelmetPrefabs {
    "{8483139372BE17EB}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P.et"
    "{7417AF432891D0CD}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Black.et"
    "{B5B0D9A175B68374}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Black_BlueVisor.et"
    "{08641D118159575A}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Black_ClearVisor.et"
    "{86DEA15534200467}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Black_OrangeVisor.et"
    "{D5BF3133E052DC02}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_BlueVisor.et"
    "{11F37C6EAEA90BAB}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_ClearVisor.et"
    "{A7148BE4E1F29FA5}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_OrangeVisor.et"
    "{BC9CCE215B093DE0}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield.et"
    "{90731F39EBF04E8C}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_Black.et"
    "{FD4F9F7CC2AF1386}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_Black_BlueVisor.et"
    "{BF410E396E205DCB}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_Black_ClearVisor.et"
    "{7152A1037546D8F1}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_Black_OrangeVisor.et"
    "{0051A9E60A0642EB}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_BlueVisor.et"
    "{BE6AB1005A20E8EA}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_ClearVisor.et"
    "{181D79DCDC19CF62}Prefabs/Characters/HeadGear/AUS_Helmet_HGU-56P/AUS_Helmet_HGU56P_Shield_OrangeVisor.et"
   }
  }
 }
}