SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_AvailableActionContext "{6620DEADBEDA5842}" {
   m_iTimeForHide 0
   m_aConditions {
    CAV_HunterKillerHintCondition "{6620DEADBEDA5844}" {
    }
   }
   m_sTag "CAV_HunterKillerSlew"
   m_sAction "CAV_HunterKillerSlew"
   m_sName "Hunter-Killer slew"
  }
  SCR_AvailableActionContext "{6620DEADBEDA5845}" {
   m_iTimeForHide 0
   m_aConditions {
    CAV_HunterKillerHintCondition "{6620DEADBEDA5846}" {
    }
   }
   m_sTag "CAV_HunterKillerCancel"
   m_sAction "CAV_HunterKillerCancel"
   m_sName "Hunter-Killer cancel"
  }
 }
}
