SCR_MissionHeader {
 World "{EB855CDBD89C67C2}Worlds/7Cav_SB_AlHadra.ent"
 m_sName "7Cav Sandbox Al Hadra"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_fPerceptionSafe 1.5
 m_fPerceptionVigilant 3
 m_fAimAccuracyErrorModifier -0.7
}