SCR_MissionHeader {
 World "{5D590CB1FC053F60}Worlds/7Cav_SB_Serhiivka.ent"
 m_sName "7Cav Sandbox Serhiivka"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{BE06FA5ABAE2B54E}Assets/cav2.edds"
 m_sLoadingScreen "{BE06FA5ABAE2B54E}Assets/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}