SCR_AvailableActionsDisplay {

 m_aActions {

  SCR_AvailableActionContext "{68E3222000000001}" {

   m_aConditions {

    HMD_IsBinocularGadgetHeldCondition "{68E3222000000002}" {

    }

   }

   m_sTag "HMD_LASER_DESIGNATE"

   m_sAction "HMD_LaserDesignate"

   m_sName "Toggle laser marker"

  }

  SCR_AvailableActionContext "{68E3222000000003}" {

   m_aConditions {

    HMD_IsBinocularGadgetHeldCondition "{68E3222000000004}" {

    }

   }

   m_sTag "HMD_LASER_CODE_INC"

   m_sAction "HMD_LaserCodeIncrement"

   m_sName "Increase laser code"

  }

  SCR_AvailableActionContext "{68E3222000000005}" {

   m_aConditions {

    HMD_IsBinocularGadgetHeldCondition "{68E3222000000006}" {

    }

   }

   m_sTag "HMD_LASER_CODE_DEC"

   m_sAction "HMD_LaserCodeDecrement"

   m_sName "Decrease laser code"

  }

  SCR_AvailableActionContext "{68E3222000000007}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000008}" {

     m_ePolicy VISIBILITY

    }

   }

   m_sTag "HMD_HUD_LASER_VISIBILITY"

   m_sAction "HMD_HUDLaserVisibilityToggle"

   m_sName "Toggle HUD laser designation visibility (others' lasers)"

  }

  SCR_AvailableActionContext "{68E3222000000017}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000018}" {

     m_ePolicy MARKING_OR_VISIBILITY

    }

   }

   m_sTag "HMD_HUD_IFF_MARKERS"

   m_sAction "HMD_HUDIffMarkersToggle"

   m_sName "Toggle IFF markers"

  }

  SCR_AvailableActionContext "{68E3222000000009}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000010}" {

     m_ePolicy MARKING

    }

   }

   m_sTag "HMD_HUD_LASER_MARKING"

   m_sAction "HMD_HUDLaserMarkingToggle"

   m_sName "Toggle HUD laser marking (rangefinder / designate)"

  }

  SCR_AvailableActionContext "{68E3222000000011}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000012}" {

     m_ePolicy MARKING

    }

   }

   m_sTag "HMD_LASER_LOCK_SEARCH"

   m_sAction "HMD_LaserLockSearchToggle"

   m_sName "Cycle HUD lock through laser designations in camera view (LSHIFT)"

  }

  SCR_AvailableActionContext "{68E3222000000013}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000014}" {

     m_ePolicy MARKING

    }

   }

   m_sTag "HMD_LASER_LOCK_REMOVE"

   m_sAction "HMD_LaserLockRemove"

   m_sName "Remove HUD laser lock"

  }

  SCR_AvailableActionContext "{68E3222000000015}" {

   m_aConditions {

    HMD_VehicleHudLaserSeatCondition "{68E3222000000016}" {

     m_ePolicy MARKING

    }

   }

   m_sTag "HMD_LASER_LOCK_SLEW"

   m_sAction "HMD_LaserLockSlewToTarget"

   m_sName "Slew turret/camera to locked laser designation (Numpad 8)"

  }

 }

}
